Detect config variable for specifying cross origin requests for map t…
GeoNode/geonode-client pull request #179
Opened 2017-08-22 15:49 UTC by travislbrundage

…ile requests in viewer

## Whart does this PR do?
Gives the Viewer the capability to specify that the SDK should make cross origin requests. This is added in a property granted via a settings boolean in GeoNode, `CROSS_ORIGIN`.

This PR requires the SDK PR merged: https://github.com/boundlessgeo/sdk/pull/618
It also coincides with the GeoNode PR: https://github.com/GeoNode/geonode/pull/3222

## Screenshot
N/A

## Related Issue
[NODE-1082](https://issues.boundlessgeo.com:8443/browse/NODE-1082)

2017-08-22 16:03 UTC, travislbrundage commented
One small mistake - fixing real quick

2017-08-23 08:27 UTC, bartvde commented
@travislbrundage doesn't the composer need the same set of changes?

2017-08-23 10:32 UTC, milafrerichs commented
I'm curious where this is being used? Only see that there is a new property. 
why would we need that? Since the client is always hitting remote services (even geonode) CORS would be needed anyway.

2017-08-23 11:01 UTC, bartvde commented
@milafrerichs some of the deploys need different crossOrigin settings, i.e. ```use-credentials``` 

I believe this is using GeoAxis

2017-08-23 11:09 UTC, bartvde commented
Ah I see the confusion probably comes from the naming of ```CROSS_ORIGIN```

We should probably rename this to CROSS_ORIGIN_USE_CREDENTIALS or CORS_USE_CREDENTIALS?

2017-08-23 11:32 UTC, milafrerichs commented
@bartvde yes, that makes more sense. 

relates to this here: http://openlayers.org/en/latest/apidoc/ol.source.TileWMS.html
and therefore this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin

so the options are `anonymous` or `use-credentials`

and one of your servers/WMS needs to use credentials which are stored as a cookie?

2017-08-23 11:32 UTC, bartvde commented
correct @milafrerichs

2017-08-23 11:37 UTC, milafrerichs commented
ok, makes more sense. then yes, please change it to a different name, otherwise this will be more confusing.

2017-08-23 11:38 UTC, milafrerichs requested changes
please rename to somethign like `crossOriginCredentials` and the geonode setting to `MAP_CLIENT_USE_CROSS_ORIGIN_CREDENTIALS` or similar as suggested in the GeoNode issue.

2017-08-23 23:39 UTC, travislbrundage commented
Updated with your feedback. Included the composer and changed the variable names to be more specific. Thanks for reviewing!

2017-08-24 07:17 UTC, milafrerichs approved these changes

2017-08-24 08:25 UTC, merged